[dev]
  publish = "_site"
  command = "npm run dev"
[build]
  command = "eleventy"
  functions = "netlify/functions"
  publish = "_site"
[[redirects]]
  from = "/add"
  to = "https://github.com/whitep4nth3r/womenofjamstack#add-your-profile-to-the-site"
  status = 301